platform :ios, '8.0'
inhibit_all_warnings!

target "iOSPlayerExample" do
pod 'LvModelWindow', '~> 0.1.1'
pod 'LvNormalSlider', :git => 'https://github.com/pgbo/LvNormalSlider.git'
pod 'DFVideoPlayer', '0.1.2', :subspecs => ['Vitamio']
end
